apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-kustom-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: kustomize-guestbook
    kustomize:
      version: v3.6.1
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
